### ISSUE TITLE
Unable to ambush

### ISSUE THREAD

**Issue by alburaidi** [cryogen/throneteki#1009]
I had 4 gold in my reserve. While I was defending, in the challenge phase I wanted to ambush The Hound (4), i wasn't able to, and even then, in the Marshalling phase I couldn't marshal him.

**Comment by ystros** [comment]
Offhand, I'm not able to reproduce this - was able to both marshal and ambush the Hound at appropriate moments.

1. Just to be clear, you clicked on the Hound during the challenges phase and he wouldn't go into play?
2. Could the Hound have been in your dead pile and you didn't notice (e.g. through cards like Heads on Spikes)? I've had the exact same thing happen to me in previous games and didn't notice because other characters were killed and placed on top of him in the pile.
3. Did you or your opponent play any cards that mess with the ability to put cards into play (e.g. Barring the Gates, Night Gathers)?

**Comment by alburaidi** [comment]
oh, that's why, i've must've had him in my dead pile, Thanks alot!
