### ISSUE TITLE
Initiate challenge timing issue

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#1047]
When initiating a challenge, a couple of different steps happen at once:

RRG:

> To initiate a challenge, the active player does the following. The game treats these criteria as being performed atomically (all at once), and they must all be completed together in order to initiate a challenge.

>* Announces the type of challenge ([military], [intrigue], or [power]) being initiated.
>* Announces the opponent against whom the challenge is being initiated.
>* Announces which characters (under his or her control) are being declared as attackers, and kneels them simultaneously. In order to be eligible as an attacker, a character must have a challenge icon that corresponds with the type of challenge being initiated, and the character must be standing. At least one character must be declared as an attacker to initiate a challenge. Any character with the stealth keyword that has been declared as an attacker also chooses its stealth targets at this time if its controller desires to use the stealth keyword.

To make sure abilities get triggered at the right time, the following events need to be raised simultaneously:

`onChallenge`
`onAttackersDeclared`
`onBypassedByStealth`

**Comment by ystros** [comment]
Are there scenarios where it actually matters that it's simultaneous or is doing them in sequence (as we do currently) sufficient?

I think the only place we're not quite in sequence is the `onBypassedByStealth` event.

**Comment by DukeTax** [comment]
It matters for example with Winterfell and Ghost: defending player is FP and triggers Winterfell, preventing attacking player from triggering Ghost. As it stands now, with onBypassedByStealth being raised before onChallenge, that's not possible. Other situations could be with Tyrion (Core) and future reactions that cost money.

**Comment by ystros** [comment]
Correcting the order of events should help those examples. Current, incorrect order is:

```
Player chooses challenge type
Player chooses attackers
Player chooses stealth targets
Event for choosing stealth targets is fired
Event for initiating challenge is fired
Event for declaring attackers is fired
```

Changing the order to this *should* fixed the examples you've listed:
```
Player chooses challenge type
Player chooses attackers
* Player chooses stealth targets (save off choices)
Event for initiating challenge is fired
Event for declaring attackers is fired
* Event for choosing stealth targets is fired using saved choices
```

However, you are correct per the rules that these events should be simultaneous. In the reverse case where Ghost bypasses as FP and defending player has Winterfell, Ghost should be able to trigger before the defender has a chance to prevent him by trigerring Winterfell (since both are reactions within the same window).

Unfortunately the best way to do this would be to combine all these events into one, which will make writing card implementations for them a bit uglier.
