### ISSUE TITLE
make in-hand reactions optional

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#1054]
In-hand reactions reveal game state that should remain hidden to your opponent.
(E.g., player A has Treachery in hand, player B kneels a reducer, A gets a reaction window and B a "waiting for opponent prompt". Busted.)

As we discussed, two fixes are envisaged for this:

- long term: a fully manual mode, that many competitive players will prefer anyhow
- medium term: make in-hand reactions optional, defaulting to "enabled", but overridable with check boxes both in-play and in user profies ← this is the main topic of this issue

**Comment by DukeTax** [comment]
Let's revive this a bit. As an alternative to your medium term solution, I propose an option that goes the other way. Instead of having an option to never prompt from hand, I'd like individual options for HJ, Treachery and Vengeance to always prompt to their specific triggering conditions, whether you're holding it or not.

1. HJ: an option to have any opponent played event prompt you.
2. Same for Treachery and any of its triggers.
3. Vengeance for Elia: always prompt you right before claim gets applied (and let's do away with the apply claim prompt while we're at it).

The advantage of this over your proposal is that the automation remains intact. No resolved events/triggered abilities/applied claim would have to be manually rewound (and rewinding intrigue claim when you wanted to play Vengeance for Elia would leak game state as well). The downside is there will be a decent amount of clicking through (potentially empty) prompts, although I think with a little bit of practice you'll get through it quickly.

Any thoughts appreciated. :)

**Comment by IMABUNNEH** [comment]
Please don't do away with the "apply claim" prompt. There have been plenty of instances where a challenge has been initiated incorrectly or circumstances in the challenge changed that caused IronThrone to declare the attacker a winner when they weren't. Being able to skip taking claim was the easy way out of that situation.

**Comment by DukeTax** [comment]
Another easy solution to that would be to manually set the claim value to 0.

**Comment by cryogen** [comment]
The timer (sort of) addresses this
