### ISSUE TITLE
Prompt for Nightmares in Dominance phase

### ISSUE THREAD

**Issue by stopfstedt** [cryogen/throneteki#1096]
Scenario:
I'd like to play Nightmares during the Dominance phase, to blank out my opponents Iron Throne before Dom get's calculated.
Right now, this does not seem to be possible, and Dom is calculated incorrectly as a result. This can easily be rectified after the fact, of course, but it's awkward esp if other Dom-related reactions take effect (e.g. Chamber).

It would be great if players were prompted to play Nightmares during Dom, just like Edric Storm and the Fiery Followers.

Thanks!

**Comment by ystros** [comment]
Thanks for the report. Couple issues here:

1. Rules-wise, there's no way to play Nightmares before dominance is calculated. Nightmares is an Action ability, not a reaction, so it must be played during an action window. Per the Rules Reference, the action window in the dominance phase comes after dominance is already calculated and rewarded, at which point Nightmares wouldn't help you win. Similarly, you could play it in the final action window of the challenges phase, but since the duration of Nightmares is until the end of the phase, once the dominance phase starts the Iron Throne will get its ability back. 

   See the dominance phase timing sequence: https://thronesdb.com/rulesreference#Timing_Sequence_Chart

2. As a matter of site design, Action abilities do not appear in prompts, but should be triggered directly during an action window prompt. By default the site won't stop for the dominance phase action window. You can turn on prompts for this and other action windows by going to Profile and checking the action windows you want it to stop for by default, as well as modifying it in individual games by clicking the green arrow on top of the prompt area (where it lists the current phase).

**Comment by stopfstedt** [comment]
I stand corrected. Thanks for the detailed answer.
