### ISSUE TITLE
Quentyn Martell vs Dracarys! should allow him to kill a character

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#1117]
Currently, if Quentyn Martell is killed by Dracarys!, he cannot kill anyone because his strength is reduced to 0 first, and then he's killed. This has been ruled to be incorrect, the kill and strength reduction should be applied simultaneously, so he'll be 4 STR when he gets killed and therefore should be able to kill someone.

Quote from dev:

> Hello,
> 
> Assuming Quentyn was at 4 STR prior to Dracarys being played, he will be at 4 STR when his interrupt triggers. 
> 
> Both the -4 STR and “killed if STR is 0” effects apply simultaneously (there is no moment in time at which he has 0 STR but is not killed). If the application of both of these effects will kill Quentyn, the interrupt window to his being killed opens, and any interrupts to his being killed will resolve prior to either the -4 STR or “killed if STR is 0” effects being applied.
> 
> Following this same logic, Blood of the Dragon will kill 1 STR characters and 0 STR characters simultaneously. 
> 
> Thanks!
> Danny Schaefer

**Comment by ystros** [comment]
...

This will probably be difficult to fix.

**Comment by ystros** [comment]
We've discussed this in chat before but here are a few things we need clarification on in order to fix this:
* If there are multiple burn effects happening at once, how do they interact when Quentyn is killed? E.g. Song of Summer + Blood of the Dragon + Dracarys, does Quentyn die at:
  *  5 STR (4 base + 1 from Song, then -1 from Blood and -4 from Dracarys)
  * 4 STR (Song + Blood cancel each other, normal -4 from Dracarys)
  * 1 STR (4 base + 1 from Song - 4 from Dracarys, then -1 from Blood)
  * First player chooses between 4 and 1 STR because they choose the order of how effects are applied?
  * Are there other simultaneous burn examples that would be more illustrative?
* How does this ruling interact with [Vaes Tolorro](https://thronesdb.com/card/04074)? The intent of VT is clearly if a character is killed via burn, 2 power can be moved. Given this ruling, however, it seems like - at least during the interrupt window - character STR will never be 0 prior to it being killed through burn. In which case the parenthetical could only ever fire if the character STR was 0 prior to the burn effect being triggered (e.g. Lancel or WoTN Sansa).

**Comment by mplain** [comment]
My interpretation of the ruling is that Quentyn's interrupt fires before the effects that would lower his STR to 0 would resolve in their entirety. Basically, it's an interrupt to his STR being reduced to 0, not to being killed due to having 0 STR. I have asked for clarifications twice now, now answer yet. So, assuming my interpretation is correct (I am not aware of any other viable interpretation), then answers to your specific scenarios are:
- 4 STR (that's his STR before Dracarys resolves and kills him)
- 1 STR (that's his STR before Astapor resolves and kills him)
- 3 STR (that's his STR before Dracarys resolves and kills him)

Vaes Tolorro does not work with burn effects under this ruling. Yes, this seems counter to the intent of the card. It has been pointed out to Danny, a couple months ago. No answer so far. But it is what we have now, unless Danny explicitly reverses his previous ruling.

**Comment by ystros** [comment]
Thanks for your interpretations, @mplain! I've used them as a base line to implement this ruling.
