### ISSUE TITLE
Save the kingdom

### ISSUE THREAD

**Issue by doimeadios** [cryogen/throneteki#1147]
I cannot use the new event baratheon as Challenge Action.

**Comment by DukeTax** [comment]
Could you elaborate a little on the circumstances? Did you have enough gold to pay for it?

**Comment by IMABUNNEH** [comment]
I have had the issue with this event intermittently. It's worked in 2 games. In other games, clicking it causes nothing to happen (when gold is available and legal targets are available). In the games where it worked correctly, it also bounced to hand correctly. In the several games where it didn't work, it also never prompted the bounce to hand trigger when I won dom.

**Comment by doimeadios** [comment]
its happened in both situations, with a gold and fealty up, and 2 golds with fealty knelt.

**Comment by DukeTax** [comment]
Ok thanks for reporting. Just to make sure, if you have just 1 gold and fealty standing, cards such as these won't work at that point. You need to kneel fealty in a separate action window to be able to reduce this card to cost 1. Not saying that that is the issue here (since it's been reported by multiple people now), but just wanted to clarify that.

**Comment by ystros** [comment]
The problem was that some games on the site were getting the old code prior to the card being implemented and some were getting the newer code. All games should be on the newer code now, so this should be fixed. Please re-open if you continue to have problems with it!
