### ISSUE TITLE
Make certain game messages / states more obvious

### ISSUE THREAD

**Issue by ystros** [cryogen/throneteki#1188]
It's easy to miss certain important messages in the chat log:

* Your opponent leaves while you're focused on marshaling, which itself adds more messages to the game log, making the leave message less obvious or potentially even pushing it above the top of the chat log.
* You get to 15 power and win the game during a complex challenge where multiple abilities fire.

These could be fixed either by using a different styling for these type of messages in chat log, by indicating the state on the player card, or both.

**Comment by zacchiro** [comment]
Different styling for different message priorities might make sense in general.

But I wonder if, in these two specific examples, the problem is rather that two specific game state information are visible *only* in the chat log. Wouldn't it be worth to make it more stably visible in the UI:
1. whether the game is still ongoing or has been won, and if so by whom
2. whether your opponent is still connected or not
