### ISSUE TITLE
Yoren taking control of Arya

### ISSUE THREAD

**Issue by zhansen8** [cryogen/throneteki#1427]
Used Yoren to take control of Arya from my opponents discard pile. Was not given the chance to use her reaction and add the top card off my deck to her.

**Comment by ystros** [comment]
Per the rules, you can only add a duplicate to a card if you both control and own the original card and the card being played as a duplicate. For example, if you took control of a character and had a copy of that character in your hand, you still couldn't use your card as a duplicate for the controlled character because you don't own it.

In this scenario, you control Core Arya but do not own her. Thus, you cannot bring a duplicate into play for her, even through her ability.

For the general rule, see the official FAQ: https://thronesdb.com/faq#Duplicates
For Arya specifically, mplain made a comment on ThronesDB (small print towards the bottom): http://thronesdb.com/card/01141

If you can find an official ruling that says otherwise for Arya, please let us know!
