### ISSUE TITLE
Asking for advice

### ISSUE THREAD

**Issue by fafranco82** [cryogen/throneteki#1444]
Hello,

First of all, I want to congratulate you for your magnific work with throneteki/theironthrone. When I first saw jinteki.net, I wanted to adapt it to GoT, but I could understand neither clojure nor the basic structure of a rules-enforced card game server...

And because of that I'm writing this now. I'm willing to do a web to play Star Wars Destiny. I tried to take a look at your code, but I'm totally lost and I don't know where to start looking and where to start coding. So I want to ask you for some guidelines about where to start and what are the foundations of nodejs backend for a web-base card game  I have no doubts about the frontend).

Thank you so much in advance, and thanks again for the theironthrone :)

**Comment by ystros** [comment]
Hi there!

It's been a while since I played SW Destiny (and only have played a couple games of it) so I can't really give concrete advice about game specifics. But I can give you a general overview of how Throneteki is put together.

* The entry point for lobby chat, active games list, profiles and static content is lobby.js in combination with API endpoints under sever/api. Probably won't need to mess with that much, at first.
* The entry point for an actual game is in gameserver.js. It manages most of the player connection logic. Again, probably won't need to touch it much at first. 
* Game flow is controlled via a pipeline of game steps (each implemented under server/game/gamesteps). Each step can be an automatic process (e.g. set gold to 0 during taxation phase) or one that requires player input (e.g. choose character for military claim). A step can itself have a sub-pipeline for nesting purposes (e.g. look at how Phase is implemented and used). The overall pipeline is initialized `Game.initialise` and `Game.beginRound`.
* You'll want to start your own hierarchy of card types. All cards inherit from `BaseCard`, which provides things common to all types of cards as well as methods to define abilities. In the case of GoT there are sub classes from draw and plot cards. Card implementations themselves can be found under server/game/cards. For Destiny I could foresee needing a character card, deck card, and battlefield card but you may need more types (or could get away with less) depending on differences in behavior.
* Abilities will be quite different I imagine. The timing rules for when an in-game event occurs is somewhat complicated (forced interupts, then interupts, then the triggering condition, etc see eventwindow.js). Effects that modify card state either temporarily or while a card is in play are handled through the effects engine. You may be able to get the overall feel for how those work by looking at card implementations, the effects themselves are defined in effects.js. Similarly, costs for triggering an ability are defined in costs.js.

That's kind of the birds eye view of things. I'm sure there are a lot of subtleties I'm not immediately thinking of. Probably the best thing you can do is look at how card abilities are implemented to give you a feeling for overall structure and then dig into the above areas.

We do want to update the engine at some point such that it isn't Game of Thrones specific and can be used for other games by implementing simpler modules. But as you can imagine, creating a generic engine that can run GoT, SW Destiny, L5R, etc will be challenging and it's probably quite a ways off.

**Comment by zacchiro** [comment]
@ystros: this summary would be a great start for a top-level HACKING.md file, or maybe docs/overview.md since we have that dir. What do you think?

(in the meantime, this bug report could probably be closed; the discussion can continue anyway if needed)

**Comment by cryogen** [comment]
Sure, feel free to carry on commenting on this issue and i'll close it

**Comment by fafranco82** [comment]
No problem with closing this ;) I wanted to send a email, but I don't see any one in a contact section, hehehe.

Thanks a lot for the guidelines. I will take a look.
