### ISSUE TITLE
implement The Iron Bank

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#1628]
The Iron Bank from Archmaester's Key isn't implemented and it should be.

As per previous discussion, the most reasonable UI approach to implement that card seems to be having a checkbox element on the card, defaulting to unchecked. Users can check it and, while it is checked, gold on The Iron Bank is used *first* to satisfy gold needs in the marshaling phase.

A bare bone implementation of this might be no visible clue on the card, but a menu option when clicking on the card that toggles using/not using it. (Simpler to implement, but worse than the previous option in terms of UX.)

**Comment by ystros** [comment]
While a simple on/off toggle (be it a checkbox or a menu item) could be a decent starting point, I don't think it's sufficient for a full implementation. 

Let's say you have 4 gold on the Iron Bank and want to marshal a 4-cost character. With a simple toggle, you would drain the entire 4 gold. But that may not be what you want. You may want to only spend 2 off of it this round so that it will have 4 on it again next round.

To do this without prompting the player every single time they spend gold, I think what is needed is more of a way to set a "spending limit" - gold up to the limit will be spent automatically, and then everything else will come from your normal gold pool. Like a toggle, the player should be able to chain this limit any time they want, which means simply prompting them when the marshal phase begins would not be sufficient. It probably means a menu item that either prompts them when selected, or a menu item that allows them to set the limit directly without a prompt.

The other challenge with this solution is that we need to prompt the player for interrupt / reaction cards even when they have their spending limit below the cost of the ability. For example, let's say:

* Player 1 hasn't collected income yet (0 gold pool)
* Player 1 has 1 gold on the Iron Bank w/ spending limit 0 (they want it to continue growing)
* Player 1 has a copy of Treachery in hand. 
* Player 2 uses Recruiter for the Watch (or some other cancelable ability). 
* Player 1 should receive a prompt to use Treachery, even though they have 0 spendable gold. At this point, they could set the spending limit to 1 and use Treachery, or we could make it such that interrupts / reactions ignore the spending limit entirely so they don't have to do anything.

Another solution that's been suggested is allowing the player to move gold off of the bank into their gold pool, and then add an alert if they don't spend that gold. This has similar problems to the spending limit solution when it comes to reactions / interrupts.

I've started work on encapsulating the way gold is used (methods like "return gold to treasury", "move/transfer gold", "spend gold", etc) so that The Iron Bank can work consistently, as well as looking forward a bit to the possibility of other potential "use this gold on specific thing" cards (see: Netrunner). I was waiting on a [ruling on the word "Spend"](http://www.cardgamedb.com/forums/index.php?/topic/37869-the-iron-bank-and-move-x-gold-abilities/) but the unofficial consensus seems to be that it only counts as spending if the gold returns to treasury, so I'll move forward with that.

**Comment by zacchiro** [comment]
I like the spending limit idea a lot.

And in terms of UI we already have a matching element: the +/value/- "widget" that we already use for player stats. Sure, it has never been put on a card before, but it has the advantage of being a thing already :-)

As a completely empirical tidbit. Right now I see a lot of people playing The Iron Bank, using the /token gymnastic. It might be worth to implement something quick and easy first (the toggle) and keep this issue around for a better long-term solution (the spending limit) later.
— yours truly, Captain Obvious :-)

**Comment by ystros** [comment]
FWIW, the UI isn't the sticking point at the moment (though it may be later), it's the usage of gold throughout the system. The wording requires we track:
1. The intentionality of the usage - Iron Bank can only be used when "spending" gold - which has been ruled is anything that is used to pay for marshaling, playing an event, using an ability, or moving gold from your pool to a card (bestow, Red Cloaks). Theoretically it could be used for things like Brothel Madame or Paid Off if they were usable in marshal phase.
2. The player that is triggering the usage - for example, A Meager Contribution should only move gold from the player's actual gold pool to the opponent, Loot (if it could be used during marshal phase) would not allow the opponent to use gold on Iron Bank since it's worded as "you may spend" and your opponent is not "you".

Here's my current WIP, which captures a bunch of point 1 but needs to be majorly reworked to capture point 2. https://github.com/cryogen/throneteki/compare/master...ystros:gold-encapsulation?expand=1

We could put out a quicker implementation that just did the gold doubling portion to reduce manual commands, but I suspect a partial implementation like that will lead to more complaints about it being "broken" even if we detail that it's not a full implementation in the news and on the How to Play page.

**Comment by slevin38** [comment]
This still isn't implemented.  Certainly is the most manual part of the game and makes it hard to play if you go second in marshaling phase you should have gold to use on Treachery / Hands Judgment, but don't without this implementation.

**Comment by cryogen** [comment]
It still hasn't gotten any easier to implement :)

we'd be very happy to review a pull request you might want to provide

**Comment by slevin38** [comment]
Not worried about it at all.  Appreciate all the hard work you do on the site!
