### ISSUE TITLE
double prompt when canceling events

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#1636]
scenario:
- user 1 plays an event
- user 2 has a single hand's judgement in hand (and enough gold)
- user 2 gets prompted to cancel and decides to do so
- user 2 gets prompted *again*

it happens to me systematically, and I've just witnessed other players complaining about the same issue with Words are Wind

**Comment by ystros** [comment]
Probably related:
* user 1 uses an ability
* user 2 has 2 copies of treachery in hand
* user 2 gets prompted to cancel and decides to do so
* user 2 gets prompted to use the second copy of treachery on the already cancelled event

I think the general takeaway is that events that either the ability system in general or the `TriggeredAbilityWindow` specifically should clean out interrupt choices for events that have already been cancelled.

This would also be a problem for saves vs kill / discard but there are built-in work arounds for that already (the saved card is removed from the list of cards being killed instead of merely marking the event as cancelled).
