### ISSUE TITLE
More Action Windows Prompts

### ISSUE THREAD

**Issue by Vicaroth** [cryogen/throneteki#170]
Adding a few more action prompt windows during Plot, Draw, Standing and Taxation action windows might help smooth game play.

**Comment by cryogen** [comment]
Might help to know what you want to do with those windows, as to whether I think we need them, or just to implement the cards causing you trouble

**Comment by DukeTax** [comment]
Some random things popping into my head you would/could do in standing or taxation phase:

Standing:

- Stand a character with Magister Illyrio who got locked by King Stannis.

Taxation:

- Return Arry to your hand to draw a card (gets around reserve).
- Stand a character with Magister Illyrio when you're in a Core Stannis lock (useful since Illyrio is limited once per phase so you can use him more)
- Trigger the plot Ranger's Cache.

**Comment by cryogen** [comment]
Now that a bunch of cards have been implemented, do you still think these windows are necessary?

**Comment by DukeTax** [comment]
I believe these might be two separate issues. Automation is great, it makes the game very quickly playable, and getting prompted by all kinds of reactions and interrupts makes it useful as a learning tool as well.

Separate from automation, and IMO more important than the mentioned windows standing/taxation etc. phases, is my desire to have the current "action/reaction" window after declaring defenders split into ideally three separate windows: one action window after declaring attackers, one after declaring defenders, and a reaction window to winning/losing the challenge (the D in DUCK). There are lots of board states that call for being able to take an action before defenders are declared, and separating the second action window from the reaction window is especially important. I can describe examples if needed.

**Comment by cryogen** [comment]
I've added a new window after the challenge phase begins as I came across several regularly occuring issues that were non trivial to resolve manually

If you can give me examples of why you think one between attackers declared and defenders is declared is necessary, I'll rethink it

**Comment by DukeTax** [comment]
First off, I don't think this is about automation vs manual control. The automation works great so far. It is about making sure (implemented/automated) actions can be triggered at the right moments.

Examples showing importance of action window before declaring defenders:

* A lot of times when a Targaryen player wants to Dracarys! an incoming attacker, he will want to use this action window. Since if the Dracarys! is cancelled, he still has the option the defend.

* Greyjoy vs Lannister. Greyjoy player is first, has an Asha and Raiding Longship out vs Tywin and a reducer on the Lannister side. Asha does a power challenge and stealths Tywin. Lannister wants to prevent the UO so Asha doesn't stand, but if he blocks with the reducer, Greyjoy has the first action and Longships the reducer. Luckily Lannister has a Widows Wail in hand, which he ambushes on the reducer before declaring defenders, then defends with his reducer which now can't be longshipped anymore.

Example showing importance of separating the second challenge action window from reactions to winning/losing:

* Tyrell vs Martell with Martell first. Tyrell does a Mil challenge with Knight of Flowers which Martell blocks with a Bastard Daughter. Since Martell is first he not gets prompted to do an action or reaction, so because (he thinks) he is losing this challenge decides to play His Viper Eyes and sees his opponents hand and discards a card. Now Tyrell has an action/reaction window, and decides to Highgarden his own Knight of Flowers since he only wanted to kneel some of the opposition and didn't want to win the challenge. So His Viper Eyes has now been played in a challenge that Martell didn't actually lose.
