### ISSUE TITLE
Undefined card codes being requested

### ISSUE THREAD

**Issue by cryogen** [cryogen/throneteki#1744]
The server is at some point asking for an undefined card code to be rendered causing a 404

https://user-images.githubusercontent.com/14303017/36212501-17491b8a-1172-11e8-830b-6fad754c1de1.png

**Comment by jbrz** [comment]
Ok I slacked off at work and poked around this - it's trying to fetch a card code of undefined every time you hover over the plot deck - you'll notice in the image below, it's trying to show you a preview of the "card" when you hover your mouse.  It doesn't occur when your mouse is over the draw deck.

I presume this is because plots are coded to preview to you when you hover over them - but perhaps that's also trying to be handled when they're still in the deck and facedown.  oops.  Probably an easy fix, but I gotta actually do work and stuff....later
<img width="1396" alt="screen shot 2018-02-14 at 11 32 47 am" src="https://user-images.githubusercontent.com/14303017/36215769-fef24f3a-117a-11e8-8deb-b900a7ba996f.png">

**Comment by jbrz** [comment]
I was going to try and test a fix locally, but for some reason can't get my env up and running.  Will bug discord about this later...

Possible solve: onMouseOver just needs an if-condition to check if the target card to display is, in point of fact, a card.  Should just be able to confirm by checking instance of/prototype card

**Comment by cryogen** [comment]
Thanks for looking at this, turns out it was just a property that got renamed in a refactor but that rename didn't carry through everywhere
