### ISSUE TITLE
Implement Ruby of R'hllor

### ISSUE THREAD

**Issue by CerseisAdvocate** [cryogen/throneteki#1759]
I am thinking about implementing 'Ruby of R'hllor' and asking myself what would be the best way to handle the 'name a card' part.
Where would be 2 Options as far as i can see.

1. Show a list with all cards to select one.
(would be easy to implement but the list would obviously be an unwieldy monster).

2. Open an input field  for the player to type the card in. use an auto complete function to ensure he or she selects a valid card name.

I think the second option is an overall better solution and also the closest to the way it handels in live play (I mean for that card you actually have to know how cards are named).
So I am asking the vets here for advise:

- is there already a function to open an input field?
- is there a function that returns a list of all cards?
- does anyone have advise how to implement an auto complete function?

**Comment by ystros** [comment]
We've always gravitated towards option 2 in our discussions about Ruby of R'hllor. It's just always been a low priority because not that many people seem to use it or complain it isn't implemented, and can be resolved manually fairly easily (assuming your opponent cooperates). Automating it would be great, but could be somewhat complicated.

We do have an existing autocomplete field for card names on the create / edit a deck page (take a look at DeckEditor.jsx and also Typeahead.jsx). However, this one would need to be different in that it should autocomplete to a single card name, not a particular version of the card. For example, the deckbuilder completes to "Arya Stark (Core)" and "Arya Stark (WoTN)" but here should complete to just "Arya Stark". That should be fairly easy.

The more complicated portion is getting that autocomplete field into the player prompt. I previously added the concept of "controls" to prompts - it's how the ability targeting is displayed on prompts that ask if you want to play a cancel. On the client side, this is rendered in ActivePlayerPrompt.jsx - it switches on the control type and then renders the proper React components for it. You could add a new one like 'card-name' to prompt the player to enter something.

On the server side, I imagine it would look something like this within Ruby's implementation (maybe not this exactly, but the general idea):
```javascripts
 this.game.promptWithMenu(this.controller, this, {
    activePrompt: {
        menuTitle: 'Name a card',
        buttons: [],
        controls: [
          { type: 'card-name', method: 'selectCardName' }
        ]
    },
    waitingPromptTitle: 'Waiting for opponents'
});
```

Then you'd have the client send a message to the server with the name they selected, which would go into a method named `selectCardName` on the Ruby implementation. e.g:

```javascript
selectCardName(player, cardName) {
  // do something with the card name
}
```

**Comment by hanneshelge** [comment]
Thanks for the info I will have a look at this when I find time for it.
