### ISSUE TITLE
Using Obara (SoD) after using Arianne (Core)

### ISSUE THREAD

**Issue by Xuldun** [cryogen/throneteki#1850]
When I try to use Obara after having used Arianne in that phase (challenges phase), I'm unable to use Obara's ability and cannot click & drag to resolve it manually.

**Comment by DukeTax** [comment]
Thanks for reporting. Could you elaborate on which characters you wanted to put into play as well as in which specific order? I haven't been able to reproduce this under these (vague) circumstances.

**Comment by rsmith26** [comment]
This has happened to me as well. about 20-30% of the time, I use Arianne to bring in Obara. then later in the phase when try to click on the option to use her ability, nothing happens. Meanwhile there are 1+ eligible targets in hand (such as a Dornish Spy or Southron Messanger). most times it works fine, it's just every once in a while (has happened at least 4 times since Thursday).

**Comment by ystros** [comment]
Thanks for the reports! I was finally able to reproduce it, it was related to the limit on the card not being properly reset after Obara was returned to hand as a cost. So it would happen if:
* Obara is returned to hand to bring a character in
* Arianne is returned to hand to bring Obara back
* Attempt to use Obara again to bring another character in would fail because the limit on Obara wasn't properly reset.

Fix is on the way.
