### ISSUE TITLE
General thoughts about automation vs manual control

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#48]
At the moment there is a weird mix of automation and manual control which I believe hurts the playability. For example, after declaring defenders it goes straight to challenge resolution. This basically makes Targaryen an unplayable faction right now. If they want to burn a defender this would likely change the challenge winner, causing the need for lots of stuff to be rewound, which oftentimes can be hard to do. If you want to automate the challenges themselves (which would be cool but probably very hard) you would need to include steps for every action window (which both players would need to pass consecutively before moving on) as well as options for reacting to winning/losing, interrupting or replacing claim, reacting/interrupting to keywords etc. Also all the less-important phases like standing and taxation and their action phases would need to be included. Without that this will probably be useful/playable but won’t be a serious tool for playing the game which is needed if you want it to reach jinteki heights I think. 

In the meantime it’s probably better (and easier) to at least make it possible to do everything manually. For example just kneeling a card, typing “mil” in the chatbox and handling the resolution yourself. There would need to be commands for drawing, looking at the top x cards of the top/bottom of the deck, putting any kind of tokens on cards, etc. Most of that is already implemented I believe but not all. It would more or less be like playing on OCTGN, except better because it's browser-based and has a much cleaner interface. Let me know what you think and if you need any help with game rules for example. :)

**Comment by MacrobiusTebo** [comment]
I would prefer manual control, especially for challenges phase. There are just too many possibilities for automatic to function perfectly. Maybe I think this because I play Targ mostly. In the last game, for example, I attacked alone with MIrri on an intrigue challenge. After I won the challenge, intrigue claim was taken automatically, but I really wanted to trigger MIrri's targeted kill ability. We just rewound the game a bit to compensate, but I saw his discarded card. I suppose it could work if every card's text and ability was programmed into the automation (like MIrri's targeted kill interrupt), but that seems like a lot of unnecessary work. The interface, especially being browser-based is great enough to make me want to play here, as opposed to OCTGN, which I hate. Mac owners, like me, will be happy. Thanks!!!!! Ryan

**Comment by dokempf** [comment]
I have not gathered experiences with this one yet (though with OCTGN automation), but I think that manual control is *always* better than automated control. The big issue with automation is scalability: New cards will always need implementation, in some cases even a refactoring of the existing code. Also, rules corner cases are easily missed when implementing automation.

**Comment by cryogen** [comment]
Closing this as #89 is the same as has more discussion
