### ISSUE TITLE
Make keywords optional and the order determinable

### ISSUE THREAD

**Issue by tonythetiger891** [cryogen/throneteki#526]
A person might not want to trigger insight if they have a low reserve value and a full hand. A person might not want to auto trigger renown if playing against edmure tully.

**Comment by DukeTax** [comment]
Thanks for your feedback! 

While these are valid situations, they are also quite niche. You would be clicking through a lot of extra prompts in all your games just to allow for less than a handful of specific situations. Btw, unless you feel you're at risk of getting decked, I like drawing insight over my reserve since it allows me to filter my hand, though opinions may vary. The situation with Edmure is easily solvable over the chat and using the /power x command. Still, the discussion is ongoing about the trade-off between playability and manual control.

**Comment by tonythetiger891** [comment]
While I agree with what you are saying about most situations being niche,
it does change the game and give an added advantage to the person drawing.
If they have a 3 reserve from a choke deck and 6 cards in hand and they
announce that they won't be taking insight before they draw... well then
they have an advantage of knowing what their next card is, which is
absolutely massive. A simple prompt would solve this. I've been in this
situation many times with Daenerys and Renly.

**Comment by zacchiro** [comment]
I think we both need to address this need *and* avoid an extra prompt which will be useless in 99% of cases. So, to note down here what I've suggested in the chat, here's a UI proposal that could address at the same time both tose needs.

- we add a per-player UI element in the form of a checkbox, that might be called "auto trigger keywords", or something like that
- the checkbox is ticked by default for both players
- as long as the checkbox is ticked, all keywords that do not need further choices by the player (renown, insight, pillage, etc.) trigger automatically without any prompt
- as long as the checkbox is *not* checked, the corresponding player is always asked whether they want to activate a specific keyword or not

This will allow to have a sane default (which is what most people will want most of the time), as well as a non-annoying way out for those rare situations where you want to act differently.

Possible improvements over the idea might be:
- make the initial value of the checkbox a user-configurable option, so that players that *always* want to be asked can have that
- make the checkbox keyword-specific, i.e., one for pillage, one for renown, etc.

**Comment by tonythetiger891** [comment]
That sounds like a wonderful idea.

On Tue, Mar 7, 2017 at 4:40 AM, Stefano Zacchiroli <notifications@github.com
