### ISSUE TITLE
Action Window during plot phase

### ISSUE THREAD

**Issue by ShunSokaro** [cryogen/throneteki#527]
Hi there!

Don't know if it's the good place to post, here are some problems I encountered when playing on throneteki:

- Maester Lomys: The game offers you to discard a card each time you win a challenge as defender, not only during intrigue challenge.

- Action windows: As a NW player, I miss action windows during plot / draw phase, particularly with a Old Forest Hunter. When I use Counting Coppers, it draw 5 cards, so it's not easy to say " I would like to discard during plot phase", because some cards were drawn during draw phase.

Another action window I have a problem with ( but which is probably reported by some other players): when a player passes during challenge action, and his opponent makes an action, if this second player clicks on "Done", the first one doesn't have the possibility to make another action. It's a problem when you have several strength boosts for example. If I win a challenge, I won't play a strength boost and pass, but if my opponent boosts one of his characters, I would like to be able to do the same after him.

Thanks !

**Comment by DukeTax** [comment]
- Maester Lomys fix: #529 
- I sympathize with your need for extra action windows, especially because the specific situation you describe is not solvable manually, your opponent would have to trust you to not discard cards drawn in the draw phase. Still, it would introduce a lot of clicking for players that are not playing the Old Forest Hunter. We'll see what cryogen says.

**Comment by cryogen** [comment]
Old forest hunter is implemented now, closing this unless any more cards require this super niche action window
