### ISSUE TITLE
Duplicates shouldn't save automatically

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#594]
I might want to use Bodyguard or Iron Mines first, and keep the dupe.

Maybe keep dupes automated but ask for other saves first.

**Comment by zacchiro** [comment]
I agree that automatic save by dupe is suboptimal, as users might want to save in other ways.
On the other hand, being asked, say, 4 times (duplicate, Bodyguard, Iron Mines, Maester Aemon) how you want to save a character would be super annoying in terms of UI.

I wonder if the right UI choice here wouldn't rather be prompting the user with something like "how do you want to save this character?". With options like the 4 mentioned above, plus an additional "don't save" option.

I anticipate implementing this would be currently hard, but that shouldn't stop us from brainstorming about the best possible UI for this :)

**Comment by mplain** [comment]
Another option is to ask per save card, not per character. This is relevant for Valar and mil claim 2+. Start by asking: "Do you want to trigger Iron Mines to save any character?" and giving a list of characters that would be killed and are eligible to be saved. Same with Risen and Maester Aemon. Then, proceed to Bodyguards and duplicates.

**Comment by ystros** [comment]
#811 now prompts for other saves prior to automatically using dupes. So you'd be prompted to use a Bodyguard if attached instead of just discarding the dupe with no input. The dupe will still be used automatically if no other save is activated.

#811 also introduces a framework to implement Iron Mines / Aemon / etc like you suggest - giving you a list of who you can save instead of asking one at a time. Will work on that next after it is merged.

**Comment by ystros** [comment]
#838 implemented the new save prompts, should be available on the next deploy!
