### ISSUE TITLE
Leave game / concede

### ISSUE THREAD

**Issue by milchteee** [cryogen/throneteki#596]
Could you implement a prompt for people exiting the tab / Leaving game that asks if they would like to concede first? It would help a lot for stat tracking and make people seem less rude if/when they leave. (even if they really are)

"Would you like to concede the game before leaving?"

**Comment by cryogen** [comment]
This is now done and live

**Comment by milchteee** [comment]
Amazing!

**Comment by milchteee** [comment]
It doesn't seem to work the way I envisioned. It just asks if I'm sure I want to leave, and then I hit OK. Does it auto-concede when I do that? 

Feature also doesn't work when X-ing out of the tab.

**Comment by cryogen** [comment]
It did work that way to start with but due to (pretty legitimate) complaints I changed it to the way it is now.  Until we have a way to work out whether your opponent is just sitting idle, it's unfair to make people concede to get away from a 'stale' game.

As for closing the browser tab, that will show as a disconnect rather than a leave, so nothing changes there.

**Comment by milchteee** [comment]
Maybe don't force it then. How about something like this when you attempt
to leave:

Would you like to concede before leaving?

Yes (concedes then leaves)
No (leave without conceding)
Cancel (cancels prompt)
