### ISSUE TITLE
Randyll Tarly - automate his standing ability

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#649]
I understand it's easy to stand him manually, but I'm somewhat concerned that players might lose track of his "Limit twice per phase".

**Comment by ystros** [comment]
If anyone wants to try their hand at this before I get to it, here's some background information about why this card hasn't already been implemented.

In order to handle conditional effects (e.g. "While there is a Summer plot") and state-dependent effects (e.g. Tywin gets +1 strength for each gold in your pool), such effects are recalculated at least once per game step. This recalculation is done by totally unapplying the effect, then applying the effect if the condition has been met. This is invisible to the user, but a card like Randyll Tarly would see its strength fluctuate, leading to a lot of false positives. For example, while the Song of Summer plot is out, Randyll would attempt to trigger over and over because the +1 strength bonus is continually reapplied.

The following changes to the effects engine need to be made to fix this:

1. Conditional effects should only be unapplied or reapplied when the result of the `condition` function changes instead of every game step.
2. State dependent effects such as `dynamicStrength` should get a `reapply` method that will apply the effect by looking at the difference between what has currently been applied and what the new value should be. So with Tywin, for example, the `reapply` function would add 1 strength when the player gains 1 gold, instead of reseting him to default strength and then increasing it again to the full amount.

Additionally,  effects that modify strength will need to call a method that to raise an `onStrengthModified` event instead of just modifying the strength modifier directly.

**Comment by ystros** [comment]
I have Randyll working locally. #702 fixes the effects engine problem discussed above, will PR the strength change and Randyll implementation after it is merged.
