### ISSUE TITLE
make stealth-ed characters more visually clear

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#742]
At the moment stealth-ed characters get a thin red border to indicate they can't be declared as defendants. It is not very visible, and players missed it almost all the times, resulting in repeated spurious kneel/stand game actions.

We should make stealth-ed characters more visually apparent.

UI proposal to fix this: add a transparent "forbidden" sign on top of the relevant characters during the "select defenders" step.

**Comment by ystros** [comment]
I agree, it's really easy to miss being bypassed by stealth unless you're watching chat like a hawk.

An overlay icon may be a good approach specifically for stealth-bypassed characters since its a special condition.

We could also take a general approach of making it more clear what characters are selectable. Here's a brief test I put together where non-selectable cards are greyed out:
![screen shot 2017-04-09 at 11 49 22 am](https://cloud.githubusercontent.com/assets/145077/24840054/db2b4912-1d1a-11e7-96fb-4ae84f556426.png)

Finally, it may be worthwhile to disabling click-kneeling and menus during card select prompts. I can't really think of a use case where kneeling a card or activating an Action ability is valid while you're being prompted to select a card, but maybe I'm missing something.

**Comment by zacchiro** [comment]
On Sun, Apr 09, 2017 at 12:00:11PM -0700, Brian Upton wrote:
> We could also take a general approach of making it more clear what
[...]
> Finally, it may be worthwhile to disabling click-kneeling and menus

+1 on both proposals: greying out non-selectable cards, and disabling
click-kneeling. They look like more generic solutions to the problem at
hand here.

**Comment by cryogen** [comment]
Standing characters to let them be selected because a non implemented ability is a valid use case and the reason I've not taken this step so far

**Comment by cryogen** [comment]
(but please go ahead with the greying out thing, looks cool)

**Comment by ystros** [comment]
FYI, I ran into a wall on this because the selectable state is incorrectly limited to the current player right now. That is, if I'm being prompted to select an opponent's card, I can't see the glow (but my opponent can). I think the intention was to hide selectable state when I'm not the player doing the selecting, but it's just broken in a different way.

Really what's needed is a `selectableBy` property that records the player doing the selection. But that means passing in the player object into all of the getSummary/getState methods instead of just the boolean isActivePlayer flag. Kind of a mess to fix, so I've stalled on it.
