### ISSUE TITLE
show Alliance banners while in game

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#889]
Decks that run the Alliance agenda do not show the banners that are being run while in-game.
This forces Alliance players to declare their banners in the game log, and their opponent to trust them :-)

We should show, somewhere near the Alliance agenda, the list of banner cards being run. Maybe as a stack of overlapping cards, as we do for attachments? That would allow to hover over the banners, and see them magnified as usual.

**Comment by cryogen** [comment]
FYI I'm looking at this as part of the deckbuilder rewrite

**Comment by ystros** [comment]
While I kind of like the idea of showing them like we do attachments, that'll require quite a bit of UI reworking. For now, I've implemented this in #1194 as the same style popup menu as the discard / dead piles.

We can keep this open if we want to ultimately move to the other proposed UI. Mostly, I needed the infrastructure in place for having cards under the agenda in order to implement The Conclave.

**Comment by zacchiro** [comment]
For me this bug was about allowing players to see the banners, no matter *how* the info is shown. Hence, I consider it can now be closed as a consequence of #1194.

If people want a different/better UI way of showing the banners, they can open a dedicated bug report about it.
