### ISSUE TITLE
Manual control debate

### ISSUE THREAD

**Issue by MacrobiusTebo** [cryogen/throneteki#89]
I'm still feeling very strongly that a full manual mode would be best here. The automation ends up very fast making things messy and confusing. There are hundreds of problems every game that the auto functions cause. The interface is great so far and I would love to see this be usable and get really popular, so I don't have to play on OCTGN any more.

Anyone else have thoughts about this?

**Comment by doomnote** [comment]
Did you mean to say a Full Manual Mode would be best? That seems to be what you're describing so a little confused.

I would 100% agree. I think making every single card automatic is a mountain of code that will just continue to grow as new cards come out and requires a ton of bug fixing as things interrupt each other and cause problems. Also, things like Keywords, which are fully automated already, are optional triggers so probably should never be automatic. The automatic challenge resolution is probably the most annoying thing right now because there is no window to play reactions, ambush, etc. which requires you to "rewind" everything and adjust. I think some smaller aspects of the game could be automatic, like gold collection, when revealed on plots, etc.

The game is pretty much in a state now where everything works if you do it manually (all mechanics exist - kneeling, dragging cards, drawing, strength modifying, etc.). Just need to be able to drag cards from other player's areas into our own. So yes, if there was a setting to turn off all the automation and just play normally I think it would be better in the long run.

**Comment by MacrobiusTebo** [comment]
Yes, that's exactly what I was trying to say, thanks. I changed my typo to say 'manual'. Sorry for the confusion. I agree with everything you say. :)

**Comment by ystros** [comment]
I think in general automation is the way to go. Things are weird currently because a tiny portion of cards are automated and there isn't a good framework in place for actions / reactions / interrupts. It's very much in an in-between state which causes friction.

I think adding some explicit action windows in the challenge phase would go a long way toward addressing at least some of the frustrations. There's so much that can happen in those 3 windows to modify the outcome that zooming through it can mess things up a lot.

The biggest challenge to automate will be interrupts. So far I'm not sure how it could be implemented without giving away information to your opponent about what you may have in your hand. You could pause the game to allow the player to play their interrupt when the game detects it's allowed to be triggered, but that would let the opponent know that they HAVE an interrupt to play. Don't have a good answer here.

**Comment by doomnote** [comment]
@ystros The only way to do that, if everything is to be automated, is to have breaks in between each step that the player must click to close, regardless if they have any interrupting cards or not. Otherwise, as you said, information would clearly be given away. This alone is my main argument for not automating everything. I think automation is fine for some things, but not every single card - the game just has too many interrupts and timing issues that will be an endless trail of coding. And the game is only a year old with hundreds of more cards to come out that could just cause more issues with automation. The next pack is already introducing an entirely new keyword and game mechanic (bestow).

**Comment by cryogen** [comment]
It's totally fine for automation to be imperfect and not handle every case. As long as the system provides ways to work around it.  Jinteki manages to get the balance right for netrunner, so there's no reason we can't do the same here.  Yes the game is slightly more complicated, but the annoying edge cases dont come up that often (once most things are implemented, it's not fair to judge it right now)

**Comment by dokempf** [comment]
Ups, just seen this one after replying to the old one. So, sorry for double posting, but I think its good to have discussion in one place.

I am a huge fan of manual control.
* The big issue with automation is scalability: New cards will always need implementation, in some cases even a refactoring of the existing code. Also, rules corner cases are easily missed when implementing automation.
* Manual control is very close to a live game for me: Game implementation just offers me the possibilities of my hands, a table and a deck of cards as opposed to trying to be smarter than me.

Note, I don't want to be a troll here, I appreciate all the efforts you are putting into this (and from a software development point of view I can totally understand that automation is intriguing)

**Comment by cryogen** [comment]
I think it's important to bear in mind that I don't intend for the game to be fully automated.  If you look at jinteki.net it implements the basic rules of netrunner, and card abilities, but it's just a starting point. There are several nuances that are not automatic and some things that it gets wrong.  And this is ok.  My goal is to have the game be playable and the simple cases to be handled for you.  Some of the more complex actions will need you to either unwind or carry our yourselves.  It's too early to properly discuss whether it works or not because it's simply not in the place i want it to be yet :)

**Comment by doomnote** [comment]
My only concern is there are things now that are currently automated that should never be - namely keyword resolution and challenge resolution. In a mostly casual game, this probably isn't a huge deal, but for the competitive players using online play to practice for in-person events, every timing window and optional trigger matters. You can see the thread on the AGOT 2.0 FB Group discussing this as well (probably where the surge of new players has come from).

It seems a happy medium would be to have buttons that do things for you if you want them to (perhaps submenus that open when clicking on cards: Kneel, Add Gold, Add Power, etc.), but not having the game resolve and assign things for you automatically. So I could click the **Military** button and declare a military challenge, saving me from typing "mil for 3" in the chat box, but clicking that button doesn't make anything happen automatically.

**Comment by OniNoOdori** [comment]
There is only one aspect of automation that I really want to see, and that is a correct implementation of the turn sequence. One major draw-back of playing online is that it is difficult to communicate at which stage of the turn you are. For example, you may wait for an opponent to take an action or pass, because you want to use your own action. Then, he or she just skips the action window and moves on to the next phase, making it necessary to rewind the game.

Ideally, it should always be made explicit when challenge keywords can be processed, when there is an action window, etc. This is the kind of automation I want, as it lets you avoid discussions about missed triggers, and even helps newer players learn some nuances of the game. I don't care how much else of the game is taken care of by the system. I just want a simple and intuitive way to navigate through a turn without the need of rewinding, and I believe that this should be a priority.

I just saw in the chat that you removed the action window after declaring attackers. This is supposed to make the game simpler, but I strongly believe that it is a step backwards. The action windows are there for a reason, and the advantage of a digital platform is that it makes these less prominent rules easier to follow. Instead, you might consider adding a way of skipping them, for example a button that can be activated if you don't want to take any actions during that phase or turn. Magic Online does something very similar with its turn sequence, and it works well, once you get used to it.

**Comment by cryogen** [comment]
The intent is not, and has never been to replicate the table top experience 100% to the rules as written.

It should be possible to play a reasonably simple game without clicking 1000 times to get through the flow.

At the same time, it should be relatively trivial to fix mistakes due to non implemented cards or the simplified flow getting things wrong.  The multiple window in challenges did not fit into this well enough for me so I've taken it out and will keep it under review

We're not were I want to be yet, but we're getting there.  If you hate it when I'm done then that's ok(so long as it's not the majority, obviously), it will always be contentious.

**Comment by OniNoOdori** [comment]
Thanks for your reply. I take no issue in you having a different perspective on the way the game should be implemented, and applaud you for staying true to your own vision. You will understand that a project like this attracts different people with individual needs and wishes. I hope that my comment didn't come off as too negative (it probably did), since I really appreciate the time and effort put into this site. Keep doing it your own way and let the whole community judge the final outcome.

Well, here's my two cents anyway, but please feel free to ignore them, if you wish:
'clicking 1000 times to get through the flow' makes it sound like there is a trade-off between staying close to the written rules and functionality. This is true to some extent, but there are different ways to alleviate this. For example, you could allow players to set 'stops' for action windows during which they plan to use an action. When there is no stop set, the program will automatically skip that action window. Admittedly, this still requires some additional clicking, but is that really worse than typing 'any actions?' in the chat the whole time? This latter option isn't faster, it just seems that way, because it is not part of the client's interface.

**Comment by cryogen** [comment]
Absolutely, and if it sounds like I'm shouting down other opinions that I apologise as that isn't my intent.  I fully expect to(and already have) take a lot feedback on board from the people who use the site, but as you say there are differing opinions.

I guess my point is that I want to get a good number of cards working, so it's apparent where the real issues are, and then decide how to address them.  Right now a lot of people are reacting to the lack of card implementations and judging the platform as a whole on that, which is fair, but I'm thinking bigger picture.

**Comment by cryogen** [comment]
Rest assured I follow these discussions closely and will try and please as many people as possible, including myself!

Wait, that just sounds wrong..

**Comment by doomnote** [comment]
I've probably been the most vocal to you about this cryo and I hope I haven't become the annoying user that you wish would stop playing - my concerns only come from a place of wanting as many people as possible to play here. What you've created so far is amazing and even with the bugs, on a completely different level than OCTGN in my opinion.

Anywho - I thought the action window prompts were a perfect solution to providing a window to play events, but I understand not wanting to click 1000 times if you don't plan on doing anything the whole turn. Which again goes back to the problem of only having a "stop" when you plan on doing something completely gives away the element of surprise. Hopefully you're at least leaving the claim prompt in, as auto discarding for int was the biggest issue as it revealed a card that shouldn't have been revealed.

At this point though I think I'll just let you do your thing and trust it will be good.

**Comment by cryogen** [comment]
Absolutely not, let me be clear I haven't been annoyed by anyone's comments so far.  I'm listening, I promise :)

I took the window out because I thought it was redundant, I think there's still places in the flow to do those things now, and the window before winner is determined is staying so things can be fixed before the game works out who won, so I think it's a good compromise.  Like I say if it turns out that that isnt the case I'll look at it again.

Don't worry the claim prompt isn't going anywhere, that one is vital.  The only reason it took so long to put in, is @ystros completely reworked the prompt system for us to be much more streamlined and easier to add prompts.  I  was waiting for him to finish so I didn't create more work for him and waste effort.

**Comment by doomnote** [comment]
After going through all the cards and adding them to the implementation list, I started thinking: I'm not sure what the plan is on this because I can't think of any cards that are currently implemented this way, but I think it's important that anything not Forced (Reaction, Interrupt, Action, etc.) must require some kind of user input to initiate. Like clicking on the card to open a submenu or activate their ability. Only Forced triggers should be 100% automated without any user input. 

I think this keeps things mostly automated and also solves the problem of the game remembering everything for you, as you have to actually click on the character, location, attachment, or event to trigger it.

For the most part, automatically triggering non-forced reactions isn't a big deal to rewind, but there are quite a few that involve revealing cards that would pose a problem if the player didn't want to trigger it.

**Comment by ystros** [comment]
@doomnote currently non-forced reactions and interrupts are being implemented as prompts rather than done 100% automatically, which gives the player the choice not to do the reaction/interrupt. Implemented examples include a prompt to draw 2 cards when Littlefinger is marshalled, put out a scheme plot via Rains when winning intrigue by 5 or more, Wolves Catelyn gaining power when a Stark is killed or sacrificed, and so on. In each case, the player has to explicitly say they want the ability to go through or to cancel it, though they are prompted automatically. Actions for the most part you need to explicitly trigger through a card menu already

(none of this applies to cards in the player hand - only 3 event cards have been implemented so far and you need to explicitly play them, no auto-prompt)

The reaction/interrupt prompts are definitely "the game remembering everything for you," as you said, since you're explicitly asked. I don't have a strong opinion of whether that's fine or undesirable. That said, the automatic prompt in this case is kind of a small implementation detail. I could see a way forward where the card simply keeps track of whether the triggering condition has been met and then add it as a menu item (or simply always have the menu item there and enable it as needed). Just kind of whatever direction @cryogen wants to take it in.

**Comment by cryogen** [comment]
The automatic prompt is very much where I want the platform to be heading and very important to the overall experience of the site.  Yes it's hand holding and yes it may dull your competitive edge, but it also makes the game accessible and at least prompts you that such interactions are possible and reminds you to use your cards ability.  It's a crutch that you wont have playing the game in person, but that's ok.

**Comment by cryogen** [comment]
So, I've implemented quite a lot of cards now which should give a flavour for the direction that I'm going in.  Does anyone want to reignite the debate in light of actual card implementations now being available?

**Comment by doomnote** [comment]
I think you win! hah - though it would be cool if maybe down the road there was a "competitive" mode where all of the automation is turned off but there would be available commands to do everything (/kill, /discard, etc) and then the default "casual" mode with everything "automated".

**Comment by paveldk** [comment]
Agree, part of the game if remembering all your actions/reactions. And another mode - call it competitive or manual would be a really nice addition and I believe will increase the user base as currently my mates don't want to play it because it's automated. 
However I think you've done a great job and that additional mode would be a step forward not backwards.

**Comment by Khudzlin** [comment]
One of the big problems with the automation is that it doesn't let the players choose the order in which to trigger their reactions (triggering an event before Rains of Castamere, for instance). This is a big part of the game. Add me to the group of people who'd play if there was a manual mode.

**Comment by cryogen** [comment]
A lot of the issues mentioned here are either gone or on the way to being gone.  "full manual mode" is probably not going to get done, but never say never
