### ISSUE TITLE
euron and control change

### ISSUE THREAD

**Issue by peloslargos** [cryogen/throneteki#924]
hi, there are some may issues with control change interaction like when i pick up an iron mine with euron i cannot save my characters but i can save the rival characters.
And other cases like steal great kraken, steal the wall etc..

**Comment by ystros** [comment]
Thanks for the report. I wasn't able to reproduce the situation described with Iron Mines directly, but #959 fixes a bunch of the other cases where take control was granting keywords / strength / etc to the wrong player.

Once the fix is merged and deployed, re-open this issue if you notice problems like the Iron Mines scenario above.
